class ResponseError(Exception):
    """Исключение для ответа API."""

    pass
